name: iOS binary build & upload
on:
  push:
    branches: [ app-store-deployment ]
jobs:
  build-ios:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.24.3'
      # - name: Decode signing certificate into a file
      #   env:
      #     CERTIFICATE_BASE64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
      # - run: |
      #     echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12
      - name: Install dependencies (Fastlane)
        run: bundle install
      - name: Build Flutter app
        run: flutter build ipa --debug
      - name: Commit build products
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git switch -c temp/v1.${{ github.run_number }}
          git add build/ios/ipa
          git commit -m "Build products (v1.${{ github.run_number }})"
          git tag -a "v1.${{ github.run_number }}" -m "v1.${{ github.run_number }}"
          git switch --detach HEAD
          git branch -D temp/v1.${{ github.run_number }}
          git push origin --tags --verbose
          git config --local --unset user.email
          git config --local --unset user.name
      - name: upload iOS binary
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: bundle exec fastlane ios upload_ios_beta_Testflight
        env:
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          PROVISIONING_PROFILE_ID: '${{ secrets.PROVISIONING_PROFILE_ID }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          ASC_KEY_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}'
          ASC_ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}'
          ASC_KEY: '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}'
          SIGNING_KEY_PASSWORD: '${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}'
          SIGNING_KEY_FILE_PATH: 'signing-cert.p12'
      # - name: Upload app-store ipa and dsyms to artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: app-store ipa & dsyms
      #     path: |
      #       ${{ github.workspace }}/example.ipa
      #       ${{ github.workspace }}/*example.app.dSYM.zip