on:
  pull_request:
    branches:
      - main
name: "iOS Build"
jobs:
  build:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.24.3'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Commit build products
        run: |
          git config --local user.name "Jace Halvorson"
          git config --local user.email "jacehalvorson33@gmail.com"
          git switch -c temp/v1.${{ github.run_number }}
          git add -f build/app/outputs
          git commit -m "[GitHub Actions] Add build products (v1.${{ github.run_number }})"
          git tag -a "v1.${{ github.run_number }}" -m "v1.${{ github.run_number }}"
          git switch --detach HEAD
          git branch -D temp/v1.${{ github.run_number }}
          git push origin --tags --verbose
          git config --local --unset user.name
          git config --local --unset user.email
